[[plugins]] # markdownプラグイン
repo = 'tpope/vim-markdown'
on_ft = ['markdown']
hook_add= '''
  let g:markdown_fenced_languages = ['html', 'python', 'bash=sh']
  let g:markdown_syntax_conceal = 0
  let g:markdown_minlines = 100
'''
[[plugins]] # emmetプラグイン
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']
[[plugins]] # postcssのsyntax
repo = 'alexlafroscia/postcss-syntax.vim'
on_ft = ['css']
[[plugins]] # pugのsyntax
repo = 'digitaltoad/vim-pug'
on_ft = ['pug']
